# Generated by Django 4.0.6 on 2024-05-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(max_length=25)),
            ],
        ),
    ]
