# Generated by Django 4.0.6 on 2024-05-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id_director', models.AutoField(primary_key=True, serialize=False)),
                ('ci_director', models.CharField(max_length=15)),
                ('apellido_director', models.CharField(max_length=50)),
                ('nombre_director', models.CharField(max_length=50)),
                ('estado_director', models.BooleanField(default=True)),
            ],
        ),
    ]
