# Generated by Django 4.0.6 on 2024-06-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0007_pelicula_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='generos',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='generos'),
        ),
    ]
