# Generated by Django 4.0.6 on 2024-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0008_generos_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores',
            name='foto_director',
            field=models.FileField(blank=True, null=True, upload_to='directores'),
        ),
    ]
