databases:
  - name: cineUTCserver
    plan: free
    databaseName: dbcineutc
    user: santiago

services:
  - type: web
    plan: free
    name: cineUTC
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cineUTC.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cineUTCserver
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: cineutc-u13j.onrender.com



# set DATABASE_URL=postgresql://santiago:qBRT1ILGjmIOzkjg3xqIAdCg186HOJxi@dpg-cqlpkulumphs739g1oh0-a.oregon-postgres.render.com/dbcineutc